"use client";

import React, { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ShareSOAPDialog } from "./share-soap-dialog";
import {
  FileText,
  Download,
  Share,
  Star,
  Clock,
  CheckCircle,
  AlertTriangle,
  ExternalLink,
  Printer,
  Calendar,
  User,
  Stethoscope
} from "lucide-react";
import { cn } from "@/lib/utils";

interface SOAPNote {
  _id: string;
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
  highlightedHtml?: string;
  qualityScore?: number;
  processingTime?: string;
  recommendations?: string[];
  googleDocUrl?: string;
  createdAt: number;
  updatedAt: number;
}

interface SOAPDocumentViewProps {
  soapNote: SOAPNote;
  patientName?: string;
  showActions?: boolean;
}

export function SOAPDocumentView({
  soapNote,
  patientName,
  showActions = true
}: SOAPDocumentViewProps) {
  const [shareDialogOpen, setShareDialogOpen] = useState(false);

  const formatDate = (timestamp: number) => {
    return new Date(timestamp).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const getQualityColor = (score?: number) => {
    if (!score) return "bg-gray-100 text-gray-800";
    if (score >= 90) return "bg-green-100 text-green-800 border-green-200";
    if (score >= 80) return "bg-blue-100 text-blue-800 border-blue-200";
    if (score >= 70) return "bg-yellow-100 text-yellow-800 border-yellow-200";
    return "bg-red-100 text-red-800 border-red-200";
  };

  const handleDownload = () => {
    const content = `
SOAP CLINICAL NOTES
Generated on: ${formatDate(soapNote.createdAt)}
${patientName ? `Patient: ${patientName}` : ''}
${soapNote.qualityScore ? `Quality Score: ${soapNote.qualityScore}%` : ''}
${soapNote.processingTime ? `Processing Time: ${soapNote.processingTime}` : ''}

SUBJECTIVE:
${soapNote.subjective}

OBJECTIVE:
${soapNote.objective}

ASSESSMENT:
${soapNote.assessment}

PLAN:
${soapNote.plan}

${soapNote.recommendations?.length ? `
RECOMMENDATIONS:
${soapNote.recommendations.map(rec => `• ${rec}`).join('\n')}
` : ''}

Generated by MedScribe AI Assistant
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `soap-notes-${new Date(soapNote.createdAt).toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 print:space-y-4">
      {/* Document Header */}
      <div className="bg-white border border-border rounded-xl shadow-lg print:shadow-none print:border-0">
        <div className="border-b border-border bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-950/20 dark:to-indigo-950/20 rounded-t-xl p-6 print:bg-white print:p-4">
          <div className="flex items-start justify-between">
            <div className="space-y-2">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-blue-600 rounded-lg print:bg-gray-600">
                  <FileText className="h-6 w-6 text-white" />
                </div>
                <div>
                  <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 print:text-black">
                    SOAP Clinical Notes
                  </h1>
                  <p className="text-sm text-gray-600 dark:text-gray-400 print:text-gray-600">
                    Structured Objective Assessment & Plan
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-4 text-sm text-gray-600 dark:text-gray-400 print:text-gray-600">
                <div className="flex items-center gap-1">
                  <Calendar className="h-4 w-4" />
                  <span>{formatDate(soapNote.createdAt)}</span>
                </div>
                {patientName && (
                  <div className="flex items-center gap-1">
                    <User className="h-4 w-4" />
                    <span>{patientName}</span>
                  </div>
                )}
                {soapNote.processingTime && (
                  <div className="flex items-center gap-1">
                    <Clock className="h-4 w-4" />
                    <span>Generated in {soapNote.processingTime}</span>
                  </div>
                )}
              </div>
            </div>

            <div className="flex items-center gap-2 print:hidden">
              {soapNote.qualityScore && (
                <Badge className={cn("border", getQualityColor(soapNote.qualityScore))}>
                  Quality: {soapNote.qualityScore}%
                </Badge>
              )}
            </div>
          </div>
        </div>

        {/* Actions Bar */}
        {showActions && (
          <div className="border-b border-border p-4 bg-gray-50/50 dark:bg-gray-900/20 print:hidden">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Button onClick={handleDownload} variant="outline" size="sm">
                  <Download className="h-4 w-4 mr-2" />
                  Download
                </Button>
                <Button onClick={handlePrint} variant="outline" size="sm">
                  <Printer className="h-4 w-4 mr-2" />
                  Print
                </Button>
                {soapNote.googleDocUrl && (
                  <Button variant="outline" size="sm" asChild>
                    <a href={soapNote.googleDocUrl} target="_blank" rel="noopener noreferrer">
                      <ExternalLink className="h-4 w-4 mr-2" />
                      View PDF
                    </a>
                  </Button>
                )}
              </div>
              <Button
                onClick={() => setShareDialogOpen(true)}
                className="bg-blue-600 hover:bg-blue-700"
                size="sm"
              >
                <Share className="h-4 w-4 mr-2" />
                Share with Doctor
              </Button>
            </div>
          </div>
        )}

        {/* Document Content */}
        <div className="p-8 print:p-6 space-y-8 print:space-y-6">
          {/* Subjective Section */}
          <section className="space-y-3">
            <div className="flex items-center gap-3 border-b border-blue-200 pb-2">
              <div className="w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-bold print:bg-gray-600">
                S
              </div>
              <h2 className="text-xl font-semibold text-blue-700 dark:text-blue-400 print:text-black">
                SUBJECTIVE
              </h2>
              <div className="flex-1 border-b border-blue-200"></div>
            </div>
            <div className="pl-11 prose prose-sm max-w-none dark:prose-invert print:prose-black">
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-wrap print:text-black">
                {soapNote.subjective}
              </p>
            </div>
          </section>

          {/* Objective Section */}
          <section className="space-y-3">
            <div className="flex items-center gap-3 border-b border-green-200 pb-2">
              <div className="w-8 h-8 bg-green-600 text-white rounded-full flex items-center justify-center text-sm font-bold print:bg-gray-600">
                O
              </div>
              <h2 className="text-xl font-semibold text-green-700 dark:text-green-400 print:text-black">
                OBJECTIVE
              </h2>
              <div className="flex-1 border-b border-green-200"></div>
            </div>
            <div className="pl-11 prose prose-sm max-w-none dark:prose-invert print:prose-black">
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-wrap print:text-black">
                {soapNote.objective}
              </p>
            </div>
          </section>

          {/* Assessment Section */}
          <section className="space-y-3">
            <div className="flex items-center gap-3 border-b border-orange-200 pb-2">
              <div className="w-8 h-8 bg-orange-600 text-white rounded-full flex items-center justify-center text-sm font-bold print:bg-gray-600">
                A
              </div>
              <h2 className="text-xl font-semibold text-orange-700 dark:text-orange-400 print:text-black">
                ASSESSMENT
              </h2>
              <div className="flex-1 border-b border-orange-200"></div>
            </div>
            <div className="pl-11 prose prose-sm max-w-none dark:prose-invert print:prose-black">
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-wrap print:text-black">
                {soapNote.assessment}
              </p>
            </div>
          </section>

          {/* Plan Section */}
          <section className="space-y-3">
            <div className="flex items-center gap-3 border-b border-purple-200 pb-2">
              <div className="w-8 h-8 bg-purple-600 text-white rounded-full flex items-center justify-center text-sm font-bold print:bg-gray-600">
                P
              </div>
              <h2 className="text-xl font-semibold text-purple-700 dark:text-purple-400 print:text-black">
                PLAN
              </h2>
              <div className="flex-1 border-b border-purple-200"></div>
            </div>
            <div className="pl-11 prose prose-sm max-w-none dark:prose-invert print:prose-black">
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-wrap print:text-black">
                {soapNote.plan}
              </p>
            </div>
          </section>

          {/* Recommendations */}
          {soapNote.recommendations && soapNote.recommendations.length > 0 && (
            <section className="space-y-3 border-t border-gray-200 pt-6 print:border-gray-400">
              <div className="flex items-center gap-3">
                <AlertTriangle className="h-5 w-5 text-amber-600" />
                <h3 className="text-lg font-semibold text-amber-700 dark:text-amber-400 print:text-black">
                  AI Recommendations
                </h3>
              </div>
              <div className="pl-8 space-y-2">
                {soapNote.recommendations.map((recommendation, index) => (
                  <div key={index} className="flex items-start gap-2">
                    <CheckCircle className="h-4 w-4 text-green-600 mt-0.5 flex-shrink-0 print:text-gray-600" />
                    <span className="text-sm text-gray-700 dark:text-gray-300 print:text-black">
                      {recommendation}
                    </span>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* Footer */}
          <div className="border-t border-gray-200 pt-6 mt-8 print:border-gray-400">
            <div className="flex items-center justify-between text-xs text-gray-500 print:text-gray-600">
              <div className="flex items-center gap-2">
                <Stethoscope className="h-4 w-4" />
                <span>Generated by MedScribe AI Assistant</span>
              </div>
              <div>
                Document ID: {soapNote._id.slice(-8)}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Share Dialog */}
      <ShareSOAPDialog
        open={shareDialogOpen}
        onOpenChange={setShareDialogOpen}
        soapNoteId={soapNote._id}
        onSuccess={() => {
          // Could add a success callback here
        }}
      />
    </div>
  );
}
